Исламов 2.1.13
Zancrow20/dotnet-homeworks-2 pull request #17
Opened 2022-12-01 21:31 UTC by Zancrow20

2022-12-01 21:32 UTC, Zancrow20 commented
![image](https://user-images.githubusercontent.com/100205132/205163334-e5e7bfeb-c46e-4dc1-b6d9-8491df0c0f25.png)

2022-12-04 17:03 UTC, Boobl1k requested changes
решение

2022-12-04 17:03 UTC, Boobl1k commented on Homework13/Hw.13/MethodsForBenchmark.cs
> +    public string Reflection(string s) => s + s;
название метода не соответствует тому, что он делает
может стоит перенести логику вызова методов в этот класс, сделав для всех методов тут общий интерфейс?

2022-12-04 17:03 UTC, Boobl1k commented on Homework13/Hw13.Tests/CalculationTimeTests.cs
> +    [InlineData("(2 + 3) / 12 * 7 + 8 * 9", 3990, 5500)]
не слишком большие рамки для времени?

2022-12-04 17:03 UTC, Boobl1k commented on Homework13/Hw13.Tests/CalculationTimeTests.cs
> +    [InlineData("(2 + 3) / 12 * 7 + 8 * 9", 3990, 5500)]
как я понимаю в этих тестах ты намеренно избежал совпадения по кэшу, не очень красиво
может стоит сбрасывать кэш (пересоздавая инстенс приложения, например)?

2022-12-04 17:03 UTC, Boobl1k commented on Homework13/Hw13.Tests/CalculationTimeTests.cs
> +        Assert.True(secondCalculationTime <= 1500);
не слишком долго для "мгновенной" операции?

2022-12-04 17:03 UTC, Boobl1k commented on Homework13/Hw13CacheCalculator/Configuration/ServiceCollectionExtensions.cs
> +                s.GetRequiredService<MathCalculatorService>()));
что это? зачем вручную доставать сервисы? они же сами ресолвятся

2022-12-04 17:03 UTC, Boobl1k commented on Homework13/Hw13CacheCalc.Tests/Hw13CacheCalc.Tests.csproj
> +</Project>
пустой проект?

2022-12-04 17:20 UTC, Zancrow20 commented on Homework13/Hw13.Tests/CalculationTimeTests.cs
> +    [InlineData("(2 + 3) / 12 * 7 + 8 * 9", 3990, 5500)]
Тут тест не нацелен на проверку кеша. Это обычный тест для калькулятора

2022-12-04 19:36 UTC, Zancrow20 commented on Homework13/Hw13CacheCalc.Tests/Hw13CacheCalc.Tests.csproj
> +</Project>
Исправил

2022-12-04 19:37 UTC, Zancrow20 commented on Homework13/Hw13CacheCalculator/Configuration/ServiceCollectionExtensions.cs
> +                s.GetRequiredService<MathCalculatorService>()));
Исправил

2022-12-04 19:37 UTC, Zancrow20 commented on Homework13/Hw13.Tests/CalculationTimeTests.cs
> +        Assert.True(secondCalculationTime <= 1500);
Убрал Task.Delay(1000) и поменял время

2022-12-04 19:37 UTC, Zancrow20 commented on Homework13/Hw13.Tests/CalculationTimeTests.cs
> +    [InlineData("(2 + 3) / 12 * 7 + 8 * 9", 3990, 5500)]
Исправил

2022-12-04 19:38 UTC, Zancrow20 commented on Homework13/Hw.13/MethodsForBenchmark.cs
> +    public string Reflection(string s) => s + s;
Переделал Generic, Dynamic и Reflection методы

2022-12-04 21:14 UTC, Boobl1k approved these changes

2022-12-04 21:14 UTC, merged

2023-09-09 15:07 UTC, Zancrow20 reviewed
Approved

2023-09-09 15:30 UTC, Zancrow20 commented on Homework13/Hw.13/MemoryTests.cs
> +[MemoryDiagnoser]
test

2023-09-10 13:42 UTC, Boobl1k commented
норм все?)

2023-09-10 13:58 UTC, Zancrow20 commented
> норм все?)

Да, я просто кое-что тестил)